services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_fastapi
    ports:
      - "8000:8000"
    volumes:
      - .:/code 
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
