apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: NodePort
  selector:
    app: bigdatanet-backend
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 32247
      protocol: TCP